### ISSUE TITLE
docker build 5.132.0 with issues

### ISSUE THREAD

**Issue by raman777** [ronivay/xen-orchestra-docker#31] opened 2024-01-20 06:49 UTC
Hi, 
I do really appreciate your work and so I was updating (on a staging system of course) to your latest build 5.132.0.
But It has issues. CPU keep at about 100%. The log produces contineously the following errors:

![image](https://github.com/ronivay/xen-orchestra-docker/assets/61283890/c2e0bcfc-6627-4bb1-8c3b-3527c9c3e835)

I stick to 5.131.0 - so there is no issue for my environment. But maybe you want to fix it.

Thanks a lot for providing a easy-to-use CE version of Xen Orchestra to the community!

Best regards, Ralph.

**Comment by ronivay** [comment] 2024-01-20 09:21
Hey, yeah there seems to be a commit from yesterday in xen-orchestra master branch which breaks this during xo-server start. New version built last night won't therefore work so stick to an older tag for now. Will push a new version once fix is in place.

**Comment by ronivay** [comment] 2024-01-20 09:32
New version of `latest` and `5.132.0` pushed now and confirmed to work. Thanks for reporting this.

**Closed by ronivay** 2024-01-20 09:32 UTC

**Comment by raman777** [comment] 2024-01-20 18:43
up and runing. Thanx.
